name: Bond Street Distribution
favicon: null
layout_spectrum: 0.74271
typography_spectrum: 0.24855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edfdf2'
    - '#000000'
    - '#585858'
    - '#808080'
    - '#9ea5a0'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
